apiVersion: v1
kind: Service
metadata:
  name: svn
spec:
  type: NodePort
  selector:
    app: svn
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rweb
spec:
  clusterIP: None
  selector:
    app: svn
  ports:
  - port: 9000
    targetPort: 9000
